image: python:3.12

stages:
  - pages

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"
  POETRY_VIRTUALENVS_CREATE: "false"
  POETRY_HOME: "$CI_PROJECT_DIR/.poetry"

cache:
  paths:
    - .cache/pip
    - .cache/pypoetry

.default_setup: &default_setup
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install poetry
    # Optional: poetry lock --no-update
    - poetry install --no-root

pages:
  stage: pages
  <<: *default_setup
  script:
    - poetry run sphinx-build -b html doc/ public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main