name: Publish Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Publish documentation
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Poetry and dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          pip install "poetry-dynamic-versioning[plugin]"
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Build documentation
        run: |
          poetry run sphinx-build -b html doc/ doc/_build/
          touch doc/_build/.nojekyll


      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: doc/_build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
