name: Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-testpypi:
    name: Publish to TestPyPI
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Poetry and dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          pip install "poetry-dynamic-versioning[plugin]"
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Publish to TestPyPI
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi $TEST_PYPI_TOKEN
          poetry publish -r test-pypi --build

  publish-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Poetry and dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          pip install "poetry-dynamic-versioning[plugin]"
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config repositories.pypi https://upload.pypi.org/legacy/
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish -r pypi --build

